// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		// Replace this comment with your code
		int num = Integer.parseInt(args[0]);
		double currntNum = Math.random();
		int currntRun = 0;
		int countLessOrEqual = 0;
		int countMore = 0;
		double ratio;
		while (currntRun < num) {
			if (currntNum <= 0.5) {
				countLessOrEqual++;
			} else if (currntNum > 0.5) {
				countMore++;
			}
			currntNum = Math.random();
			currntRun++;
		}
		if (countLessOrEqual == 0 || countMore == 0) {
			System.out.println("> 0.5:  " + countLessOrEqual + " Times");
			System.out.println("<= 0.5: " + countMore + " Times");
		} else if (countLessOrEqual > countMore) {
			ratio = (double) countMore / (double) countLessOrEqual;
			System.out.println("> 0.5:  " + countLessOrEqual + " Times");
			System.out.println("<= 0.5: " + countMore + " Times");
			System.out.println("Ratio:  " + ratio);
		} else if (countLessOrEqual < countMore) {
			ratio = (double) countLessOrEqual / (double) countMore;
			System.out.println("> 0.5:  " + countLessOrEqual + " Times");
			System.out.println("<= 0.5: " + countMore + " Times");
			System.out.println("Ratio:  " + ratio);
		} else {
			ratio = (double) countMore / (double) countLessOrEqual;
			System.out.println("> 0.5:  " + countLessOrEqual + " Times");
			System.out.println("<= 0.5: " + countMore + " Times");
			System.out.println("Ratio:  " + ratio);
		}

	}
}
